name: Sculk Server

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      # Optionnel : Générer une image native avec GraalVM
      - name: Build Native Image
        run: |
          mvn package -Pnative
        if: success()  # N'exécute cette étape que si la construction précédente a réussi
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_artifacts
          path: |
            ${{ github.workspace }}/Sculk-1.0-SNAPSHOT-jar-with-dependencies.jar
